<?xml version="1.0" encoding="UTF-8"?>

<!--
This file gives a table of available Bible publications including
    A unique English publication publicationName (as a comment only)
        (This table should be language agnostic although English is used as a meta-language.)
    A unique reference abbreviation
    The type:   original    e.g., Hebrew/Greek scriptures
                translation e.g., 1611 King James Bible (KJB)
                revision    e.g., 1769 King James Bible
                edition     e.g., NIV Women’s Study Bible (An edition uses a translation)
    The definitive names with the language specified as an ISO 639-3 code in an attribute.
    A versificationSystem publicationName field which directs to that versification system.
    A punctuationSystem publicationName field which directs to the punctuation system.
        None and Unknown are also valid entries for the system publicationName fields.

The historical data encoded in this document is approximate only.
It’s impossible to accurately list all of the adjustments and revisions of texts that were made,
especially since the text of some early versions is no longer available.

Language codes use IETF BCP47 language tags: https://en.wikipedia.org/wiki/IETF_language_tag.

The data is preceded by a header of the same format as an OSIS header.

Note that most of the data is supplied as XML elements, not attributes.

Although an internal DTD is included, a Relax NG (RNC) schema is also supplied for better validation.

See the supplied README.md for more details.
-->

<!DOCTYPE BiblePublications [
    <!ELEMENT BiblePublications (header,BiblePublication+)>
        <!ELEMENT header (revisionDesc*,work)>
            <!ELEMENT revisionDesc (date,p+)>
                <!ELEMENT date (#PCDATA)>
                <!ELEMENT p (#PCDATA)>
            <!ELEMENT work (version,date,title,contributor+,identifier*,rights)>
                <!ELEMENT version (#PCDATA)>
                <!ELEMENT title (#PCDATA)>
                <!ELEMENT contributor (#PCDATA)>
                    <!ATTLIST contributor role (com|cre|edt) #REQUIRED>
                <!ELEMENT identifier (#PCDATA)>
                    <!ATTLIST identifier type (URL) #REQUIRED>
                <!ELEMENT rights (#PCDATA)>
        <!ELEMENT BiblePublication (referenceAbbreviation,languageCode,publicationName+,derivedFrom*,translator*,completionDate*,publicationDate*,
                        versificationSystem*,punctuationSystem*,bookOrderSystem*,booksNamesSystem*,usesText*,webLink*)>
            <!ATTLIST BiblePublication type CDATA #REQUIRED>
            <!ELEMENT referenceAbbreviation (#PCDATA)>
            <!ELEMENT languageCode (#PCDATA)>
            <!ELEMENT publicationName (#PCDATA)>
            <!ELEMENT translator (#PCDATA)>
            <!ELEMENT derivedFrom (#PCDATA)>
            <!ELEMENT publicationDate (#PCDATA)>
            <!ELEMENT versificationSystem (#PCDATA)>
            <!ELEMENT punctuationSystem (#PCDATA)>
            <!ELEMENT bookOrderSystem (#PCDATA)>
            <!ELEMENT booksNamesSystem (#PCDATA)>
            <!ELEMENT usesText (#PCDATA)>
            <!ELEMENT webLink (#PCDATA)>
]>

<BiblePublications>

  <header>
    <work>
      <version>0.29</version>
      <date>2022-08-17</date>
      <title>Bible publications list</title>
      <contributor role="com">Robert Hunt</contributor>
      <rights>Public Domain</rights>
      <identifier type="URL">https://en.wikipedia.org/wiki/English_translations_of_the_Bible</identifier>
      <identifier type="URL">https://en.wikipedia.org/wiki/List_of_English_Bible_translations</identifier>
      <identifier type="URL">https://www.biblicaltraining.org/history-english-bible/daniel-wallace/foundations</identifier>
      <identifier type="URL">https://www.lockman.org/nasb/nasbprin.php</identifier>
      <identifier type="URL">https://www.blainerobison.com/bible/bible-abbreviations.htm</identifier>
</work>
  </header>


<!-- Original compilations of Bible texts -->
  <BiblePublication type="original">
    <referenceAbbreviation>HEB</referenceAbbreviation>
    <languageCode>hbo</languageCode>
    <publicationName lang="en">Hebrew Scriptures</publicationName>
    <versificationSystem>Hebrew</versificationSystem>
    <punctuationSystem>None</punctuationSystem>
    <bookOrderSystem>Hebrew</bookOrderSystem>
    <booksNamesSystem>None</booksNamesSystem>
    <includesBooks>GEN EXO LEV NUM DEU JOS JDG RUT SA1 SA2 KI1 KI2 CH1 CH2 EZR NEH EST JOB PSA PRO ECC SNG ISA JER LAM EZE DAN HOS JOL AMO OBA JNA MIC NAH HAB ZEP HAG ZEC MAL</includesBooks>
    <webLink>https://en.wikipedia.org/wiki/Hebrew_Bible</webLink>
  </BiblePublication>

  <BiblePublication type="original">
    <referenceAbbreviation>WLC</referenceAbbreviation>
    <languageCode>hbo</languageCode>
    <publicationName lang="en">Westminster Leningrad Codex</publicationName>
    <versificationSystem>Hebrew</versificationSystem>
    <punctuationSystem>None</punctuationSystem>
    <bookOrderSystem>Hebrew</bookOrderSystem>
    <booksNamesSystem>None</booksNamesSystem>
    <includesBooks>GEN EXO LEV NUM DEU JOS JDG RUT SA1 SA2 KI1 KI2 CH1 CH2 EZR NEH EST JOB PSA PRO ECC SNG ISA JER LAM EZE DAN HOS JOL AMO OBA JNA MIC NAH HAB ZEP HAG ZEC MAL</includesBooks>
    <webLink>https://en.wikipedia.org/wiki/Leningrad_Codex</webLink>
  </BiblePublication>

  <BiblePublication type="original">
    <referenceAbbreviation>BHS</referenceAbbreviation>
    <languageCode>hbo</languageCode>
    <publicationName lang="lat">Biblia Hebraica Stuttgartensia</publicationName>
    <versificationSystem>Hebrew</versificationSystem>
    <punctuationSystem>None</punctuationSystem>
    <bookOrderSystem>Hebrew</bookOrderSystem>
    <booksNamesSystem>None</booksNamesSystem>
    <includesBooks>GEN EXO LEV NUM DEU JOS JDG RUT SA1 SA2 KI1 KI2 CH1 CH2 EZR NEH EST JOB PSA PRO ECC SNG ISA JER LAM EZE DAN HOS JOL AMO OBA JNA MIC NAH HAB ZEP HAG ZEC MAL</includesBooks>
    <webLink>https://en.wikipedia.org/wiki/Biblia_Hebraica_Stuttgartensia</webLink>
  </BiblePublication>

  <BiblePublication type="original">
    <referenceAbbreviation>OSHB</referenceAbbreviation>
    <languageCode>hbo</languageCode>
    <publicationName lang="en">Open Scriptures Hebrew Bible</publicationName>
    <derivedFrom>WLC</derivedFrom>
    <versificationSystem>Hebrew</versificationSystem>
    <punctuationSystem>None</punctuationSystem>
    <bookOrderSystem>Hebrew</bookOrderSystem>
    <booksNamesSystem>None</booksNamesSystem>
    <includesBooks>GEN EXO LEV NUM DEU JOS JDG RUT SA1 SA2 KI1 KI2 CH1 CH2 EZR NEH EST JOB PSA PRO ECC SNG ISA JER LAM EZE DAN HOS JOL AMO OBA JNA MIC NAH HAB ZEP HAG ZEC MAL</includesBooks>
    <webLink>https://hb.OpenScriptures.org/</webLink>
  </BiblePublication>

  <BiblePublication type="original">
    <referenceAbbreviation>NTG</referenceAbbreviation>
    <languageCode>grc</languageCode>
    <publicationName lang="en">Greek Scriptures</publicationName>
    <versificationSystem>KJB</versificationSystem>
    <punctuationSystem>None</punctuationSystem>
    <bookOrderSystem>Unknown</bookOrderSystem>
    <booksNamesSystem>None</booksNamesSystem>
    <includesBooks>MAT MRK LUK JHN ACT ROM CO1 CO2 GAL EPH PHP COL TH1 TH2 TI1 TI2 TIT PHM HEB JAM PE1 PE2 JN1 JN2 JN3 JDE REV</includesBooks>
    <webLink>https://en.wikipedia.org/wiki/Greek_New_Testament</webLink>
  </BiblePublication>

  <BiblePublication type="original">
    <referenceAbbreviation>BHP-GNT</referenceAbbreviation>
    <languageCode>grc</languageCode>
    <publicationName lang="en">Bunning Heuristic Prototype Greek New Testament</publicationName>
    <publicationDate>2017</publicationDate>
    <publisherName>Center for New Testament Restoration</publisherName>
    <licence>Creative Commons Attribution-ShareAlike 4.0 International License</licence>
    <versificationSystem>KJB</versificationSystem>
    <punctuationSystem>None</punctuationSystem>
    <bookOrderSystem>Unknown</bookOrderSystem>
    <booksNamesSystem>None</booksNamesSystem>
    <includesBooks>MAT MRK LUK JHN ACT ROM CO1 CO2 GAL EPH PHP COL TH1 TH2 TI1 TI2 TIT PHM HEB JAM PE1 PE2 JN1 JN2 JN3 JDE REV</includesBooks>
    <webLink>https://GitHub.com/greekcntr/BHP</webLink>
    <webLink>https://GreekCNTR.org</webLink>
  </BiblePublication>

  <BiblePublication type="original">
    <referenceAbbreviation>SR-GNT</referenceAbbreviation>
    <languageCode>grc</languageCode>
    <publicationName lang="en">Statistical Restoration Greek New Testament</publicationName>
    <publicationDate>2022</publicationDate>
    <publisherName>Center for New Testament Restoration</publisherName>
    <licence>Creative Commons Attribution-ShareAlike 4.0 International License</licence>
    <versificationSystem>KJB</versificationSystem>
    <punctuationSystem>None</punctuationSystem>
    <bookOrderSystem>Unknown</bookOrderSystem>
    <booksNamesSystem>None</booksNamesSystem>
    <includesBooks>MAT MRK LUK JHN ACT ROM CO1 CO2 GAL EPH PHP COL TH1 TH2 TI1 TI2 TIT PHM HEB JAM PE1 PE2 JN1 JN2 JN3 JDE REV</includesBooks>
    <webLink>https://GreekCNTR.org</webLink>
  </BiblePublication>

  <BiblePublication type="translation">
    <referenceAbbreviation>AMP</referenceAbbreviation>
    <publicationName lang="en">Amplified Bible</publicationName>
    <languageCode>en</languageCode>
  </BiblePublication>

  <BiblePublication type="translation">
    <referenceAbbreviation>Anderson</referenceAbbreviation>
    <publicationName lang="en">The New Testament Translated from the Original Greek</publicationName>
    <languageCode>en</languageCode>
    <publisherName>H.T. Anderson</publisherName>
    <licence>Public Domain</licence>
  </BiblePublication>

   <BiblePublication type="translation">
    <referenceAbbreviation>BBE</referenceAbbreviation>
    <publicationName lang="en">Bible in Basic English</publicationName>
    <languageCode>en</languageCode>
  </BiblePublication>

  <BiblePublication type="translation">
    <referenceAbbreviation>BHIB</referenceAbbreviation>
    <publicationName lang="en">Bible Hub Interlinear Bible</publicationName>
    <languageCode>en</languageCode>
  </BiblePublication>

  <BiblePublication type="translation">
    <referenceAbbreviation>BLB</referenceAbbreviation>
    <publicationName lang="en">Berean Literal Bible</publicationName>
    <languageCode>en</languageCode>
  </BiblePublication>

  <BiblePublication type="translation">
    <referenceAbbreviation>BRG</referenceAbbreviation>
    <publicationName lang="en">Blue Red and Gold Letter Edition Bible</publicationName>
    <languageCode>en</languageCode>
    <publisherName>BRG Bible Ministries</publisherName>
  </BiblePublication>

  <BiblePublication type="translation">
    <referenceAbbreviation>CEB</referenceAbbreviation>
    <publicationName lang="en">Common English Bible</publicationName>
    <languageCode>en</languageCode>
  </BiblePublication>

  <BiblePublication type="translation">
    <referenceAbbreviation>CJV</referenceAbbreviation>
    <publicationName lang="en">Complete Jewish Bible</publicationName>
    <languageCode>en</languageCode>
  </BiblePublication>

  <BiblePublication type="translation">
    <referenceAbbreviation>Coverdale</referenceAbbreviation>
    <publicationName lang="en">Coverdale Bible</publicationName>
    <languageCode>en</languageCode>
    <publisherName>Miles Coverdale</publisherName>
    <licence>Public Domain</licence>
  </BiblePublication>

  <BiblePublication type="translation">
    <referenceAbbreviation>CSB</referenceAbbreviation>
    <publicationName lang="en">Christian Standard Bible</publicationName>
    <languageCode>en</languageCode>
    <derivedFrom>HCSB</derivedFrom>
  </BiblePublication>

  <BiblePublication type="translation">
    <referenceAbbreviation>DBY</referenceAbbreviation>
    <publicationName lang="en">Darby Translation</publicationName>
    <languageCode>en</languageCode>
    <publisherName>J.N. Darby</publisherName>
    <licence>Public Domain</licence>
  </BiblePublication>

  <BiblePublication type="translation">
    <referenceAbbreviation>DHE</referenceAbbreviation>
    <publicationName lang="en">The Delitzsch Hebrew Gospels (translation)</publicationName>
    <languageCode>en</languageCode>
  </BiblePublication>

  <BiblePublication type="translation">
    <referenceAbbreviation>DLNT</referenceAbbreviation>
    <publicationName lang="en">Disciples Literal New Testament</publicationName>
    <languageCode>en</languageCode>
  </BiblePublication>

  <BiblePublication type="translation">
    <referenceAbbreviation>DRA</referenceAbbreviation>
    <publicationName lang="en">Douay-Rheims 1899 American Edition</publicationName>
    <languageCode>en</languageCode>
  </BiblePublication>

  <BiblePublication type="translation">
    <referenceAbbreviation>DSS</referenceAbbreviation>
    <publicationName lang="en">The Dead Sea Scrolls: A New Translation</publicationName>
    <languageCode>en</languageCode>
    <publisherName>HarperOne</publisherName>
  </BiblePublication>

  <BiblePublication type="translation">
    <referenceAbbreviation>ECB</referenceAbbreviation>
    <publicationName lang="en">exeGeses Companion Bible</publicationName>
    <languageCode>en</languageCode>
  </BiblePublication>

  <BiblePublication type="translation">
    <referenceAbbreviation>EHV</referenceAbbreviation>
    <publicationName lang="en">Evangelical Heritage Version: New Testament &amp; Psalms</publicationName>
    <languageCode>en</languageCode>
  </BiblePublication>

  <BiblePublication type="translation">
    <referenceAbbreviation>EMTV</referenceAbbreviation>
    <publicationName lang="en">English Majority Text Version: New Testament</publicationName>
    <languageCode>en</languageCode>
  </BiblePublication>

  <BiblePublication type="translation">
    <referenceAbbreviation>ERV</referenceAbbreviation>
    <publicationName lang="en">Easy-to-Read Version</publicationName>
    <languageCode>en</languageCode>
    <publisherName>World Bible Translation Center</publisherName>
  </BiblePublication>

  <BiblePublication type="translation">
    <referenceAbbreviation>EXV</referenceAbbreviation>
    <publicationName lang="en">The Expanded Bible</publicationName>
    <languageCode>en</languageCode>
  </BiblePublication>

  <BiblePublication type="translation">
    <referenceAbbreviation>GB</referenceAbbreviation>
    <publicationName lang="en">Geneva Bible</publicationName>
    <languageCode>en</languageCode>
  </BiblePublication>

  <BiblePublication type="translation">
    <referenceAbbreviation>GNC</referenceAbbreviation>
    <publicationName lang="en">God’s New Covenant: A New Testament Translation</publicationName>
    <languageCode>en</languageCode>
    <publisherName>Heinrich Walter Cassirer</publisherName>
  </BiblePublication>

  <BiblePublication type="translation">
    <referenceAbbreviation>GoodSp</referenceAbbreviation>
    <publicationName lang="en">The New Testament: An American Translation</publicationName>
    <languageCode>en</languageCode>
  </BiblePublication>

  <BiblePublication type="translation">
    <referenceAbbreviation>GNB</referenceAbbreviation>
    <publicationName lang="en">Good News Bible</publicationName>
    <languageCode>en</languageCode>
  </BiblePublication>

  <BiblePublication type="translation">
    <referenceAbbreviation>ISV</referenceAbbreviation>
    <publicationName lang="en">The Holy Bible: International Standard Version</publicationName>
    <languageCode>en</languageCode>
    <publicationDate>2015</publicationDate>
    <publisherName>Davidson Press</publisherName>
    <webLink>https://web.archive.org/web/20160616105413/https://www.isv.org/bible/</webLink>
  </BiblePublication>

  <BiblePublication type="translation">
    <referenceAbbreviation>JPS</referenceAbbreviation>
    <publicationName lang="en">The Holy Scriptures According to the Masoretic Text</publicationName>
    <languageCode>en</languageCode>
    <publisherName>Jewish Publication Society of America</publisherName>
  </BiblePublication>

  <BiblePublication type="revision">
    <referenceAbbreviation>KJB</referenceAbbreviation>
    <publicationName lang="en">King James Bible</publicationName>
    <alternativeAbbreviations>KJV,AV,AKJB</alternativeAbbreviations>
    <languageCode>en</languageCode>
    <derivedFrom>BB-1602</derivedFrom>
  </BiblePublication>

 <BiblePublication type="revision">
    <referenceAbbreviation>AKJB</referenceAbbreviation>
    <publicationName lang="en">Authorised King James Bible</publicationName>
    <languageCode>en</languageCode>
    <recommendedAlternativeAbbreviation>KJB</recommendedAlternativeAbbreviation>
  </BiblePublication>

  <BiblePublication type="translation">
    <referenceAbbreviation>KTK</referenceAbbreviation>
    <publicationName lang="en">Keys of the Kingdom Holy Bible</publicationName>
    <languageCode>en</languageCode>
    <publisherName>Christopher Sparkes</publisherName>
    <webLink>https://www.KeysOfTheKingdomBible.com</webLink>
  </BiblePublication>

  <!-- Also Luther Bible!!! How to handle this??? -->
  <BiblePublication type="translation">
    <referenceAbbreviation>LB</referenceAbbreviation>
    <publicationName lang="en">Living Bible</publicationName>
    <languageCode>en</languageCode>
  </BiblePublication>

  <BiblePublication type="translation">
    <referenceAbbreviation>LSB</referenceAbbreviation>
    <publicationName lang="en">Legacy Standard Bible</publicationName>
    <languageCode>en</languageCode>
    <publisherName>Lockman Foundation</publisherName>
    <webLink>https://lsbible.org</webLink>
  </BiblePublication>

  <BiblePublication type="translation">
    <referenceAbbreviation>LSV</referenceAbbreviation>
    <publicationName lang="en">Literal Standard Version</publicationName>
    <languageCode>en</languageCode>
  </BiblePublication>

  <BiblePublication type="translation">
    <referenceAbbreviation>MJLT</referenceAbbreviation>
    <publicationName lang="en">Messianic Jewish Literal Translation</publicationName>
    <languageCode>en</languageCode>
    <publisherName>Kevin Geoffrey, Perfect Word Messianic Publishing</publisherName>
  </BiblePublication>

  <BiblePublication type="translation">
    <referenceAbbreviation>MW</referenceAbbreviation>
    <publicationName lang="en">The Messianic Writings</publicationName>
    <languageCode>en</languageCode>
    <publisherName>Daniel Gruber</publisherName>
  </BiblePublication>

  <BiblePublication type="translation">
    <referenceAbbreviation>NASB</referenceAbbreviation>
    <publicationName lang="en">New American Standard Version</publicationName>
    <languageCode>en</languageCode>
    <publisherName>Lockman Foundation</publisherName>
  </BiblePublication>

  <BiblePublication type="translation">
    <referenceAbbreviation>OET</referenceAbbreviation>
    <publicationName lang="en">Open English Translation</publicationName>
    <languageCode>en</languageCode>
    <publisherName>Freely-Given.org</publisherName>
    <derivedFrom>OSHB</derivedFrom>
    <derivedFrom>SR-GNT</derivedFrom>
    <webLink>https://OpenEnglishTranslation.Bible</webLink>
  </BiblePublication>

  <BiblePublication type="translation">
    <referenceAbbreviation>OJB</referenceAbbreviation>
    <publicationName lang="en">Orthodox Jewish Bible</publicationName>
    <languageCode>en</languageCode>
  </BiblePublication>

  <BiblePublication type="translation">
    <referenceAbbreviation>REV</referenceAbbreviation>
    <publicationName lang="en">Revised English Version</publicationName>
    <languageCode>en</languageCode>
    <publisherName>Spirit and Truth Fellowship International</publisherName>
  </BiblePublication>

  <BiblePublication type="translation">
    <referenceAbbreviation>RGT</referenceAbbreviation>
    <publicationName lang="en">Revised Geneva Translation</publicationName>
    <languageCode>en</languageCode>
    <derivedFrom>GB</derivedFrom>
    <publisherName>Five Talents Audio</publisherName>
  </BiblePublication>

  <BiblePublication type="translation">
    <referenceAbbreviation>RSV</referenceAbbreviation>
    <publicationName lang="en">Revised Standard Version</publicationName>
    <languageCode>en</languageCode>
    <publisherName>Division of Christian Education of the National Council of the Churches of Christ in the United States of America</publisherName>
  </BiblePublication>

  <BiblePublication type="translation">
    <referenceAbbreviation>RSV-CE</referenceAbbreviation>
    <publicationName lang="en">Revised Standard Version, Catholic Edition</publicationName>
    <languageCode>en</languageCode>
    <publisherName>Division of Christian Education of the National Council of the Churches of Christ in the United States of America</publisherName>
  </BiblePublication>

  <BiblePublication type="translation">
    <referenceAbbreviation>RVA</referenceAbbreviation>
    <publicationName lang="en">Reina-Valera Antigua</publicationName>
    <languageCode>sp</languageCode>
  </BiblePublication>

  <BiblePublication type="translation">
    <referenceAbbreviation>SLT</referenceAbbreviation>
    <publicationName lang="en">Smith’s Literal Translation of the Bible</publicationName>
    <languageCode>en</languageCode>
    <publisherName>Julia E. Smith</publisherName>
  </BiblePublication>

  <BiblePublication type="translation">
    <referenceAbbreviation>TEV</referenceAbbreviation>
    <publicationName lang="en">Today’s English Version</publicationName>
    <languageCode>en</languageCode>
  </BiblePublication>

  <BiblePublication type="translation">
    <referenceAbbreviation>TPT</referenceAbbreviation>
    <publicationName lang="en">The Passion Translation</publicationName>
    <languageCode>en</languageCode>
    <publisherName>BroadStreet Publishing Group, LLC</publisherName>
  </BiblePublication>

  <BiblePublication type="translation">
    <referenceAbbreviation>UASV</referenceAbbreviation>
    <publicationName lang="en">Updated American Standard Version</publicationName>
    <languageCode>en</languageCode>
    <publisherName>Christian Publishing House</publisherName>
    <webLink>https://uasvbible.org</webLink>
  </BiblePublication>

  <BiblePublication type="original">
    <referenceAbbreviation>UGNT</referenceAbbreviation>
    <publicationName lang="en">unfoldingWord® Greek New Testament</publicationName>
    <languageCode>x-grk-koine</languageCode>
    <derivedFrom>BHP</derivedFrom>
    <publisherName>unfoldingWord®</publisherName>
    <licence>Creative Commons Attribution-ShareAlike 4.0 International License</licence>
    <webLink>https://git.door43.org/unfoldingWord/en_ugnt</webLink>
  </BiblePublication>

  <BiblePublication type="original">
    <referenceAbbreviation>UHB</referenceAbbreviation>
    <publicationName lang="en">unfoldingWord® Hebrew Bible</publicationName>
    <languageCode>hbo</languageCode>
    <derivedFrom>OSHB</derivedFrom>
    <publisherName>unfoldingWord®</publisherName>
    <licence>Creative Commons Attribution-ShareAlike 4.0 International License</licence>
    <webLink>https://git.door43.org/unfoldingWord/en_uhb</webLink>
  </BiblePublication>

  <BiblePublication type="translation">
    <referenceAbbreviation>ULT</referenceAbbreviation>
    <publicationName lang="en">unfoldingWord® Literal Text</publicationName>
    <languageCode>en</languageCode>
    <publisherName>unfoldingWord®</publisherName>
    <licence>Creative Commons Attribution-ShareAlike 4.0 International License</licence>
    <webLink>https://git.door43.org/unfoldingWord/en_ult</webLink>
  </BiblePublication>

  <BiblePublication type="translation">
    <referenceAbbreviation>UST</referenceAbbreviation>
    <publicationName lang="en">unfoldingWord® Simplified Text</publicationName>
    <languageCode>en</languageCode>
    <publisherName>unfoldingWord®</publisherName>
    <licence>Creative Commons Attribution-ShareAlike 4.0 International License</licence>
    <webLink>https://git.door43.org/unfoldingWord/en_ust</webLink>
  </BiblePublication>

  <BiblePublication type="translation">
    <referenceAbbreviation>Voice</referenceAbbreviation>
    <publicationName lang="en">The Voice Bible</publicationName>
    <languageCode>en</languageCode>
    <publisherName>Thomas Nelson, Inc.; Ecclesia Bible Society</publisherName>
  </BiblePublication>

  <BiblePublication type="translation">
    <referenceAbbreviation>WE</referenceAbbreviation>
    <publicationName lang="en">Worldwide English New Testament</publicationName>
    <languageCode>en</languageCode>
  </BiblePublication>

  <BiblePublication type="translation">
    <referenceAbbreviation>WEB</referenceAbbreviation>
    <publicationName lang="en">World English Bible</publicationName>
    <languageCode>en</languageCode>
    <publisherName>eBible.org</publisherName>
    <licence>Public Domain</licence>
    <webLink>https://worldenglish.bible/</webLink>
    <publisherLink>https://ebible.org/</publisherLink>
  </BiblePublication>

  <BiblePublication type="translation">
    <referenceAbbreviation>WMB</referenceAbbreviation>
    <publicationName lang="en">World Messianic Bible</publicationName>
    <languageCode>en</languageCode>
    <publisherName>eBible.org</publisherName>
    <licence>Public Domain</licence>
    <webLink>https://worldenglish.bible/</webLink>
    <publisherLink>https://ebible.org/</publisherLink>
  </BiblePublication>

  <BiblePublication type="translation">
    <referenceAbbreviation>WNT</referenceAbbreviation>
    <publicationName lang="en">Weymouth New Testament</publicationName>
    <languageCode>en</languageCode>
  </BiblePublication>

<!-- Translations from originals, and -->
<!-- Revisions of earlier translations -->
  <BiblePublication type="translation">
    <referenceAbbreviation>LXX</referenceAbbreviation>
    <languageCode>grc</languageCode>
    <publicationName lang="en">Septuagint Translation of the Hebrew Bible</publicationName>
    <publicationName lang="en">LXX</publicationName>
    <publicationDate>300 BC</publicationDate>
    <derivedFrom>HEB</derivedFrom>
    <versificationSystem>Septuagint</versificationSystem>
    <punctuationSystem>None</punctuationSystem>
    <bookOrderSystem>Septuagint</bookOrderSystem>
    <booksNamesSystem>None</booksNamesSystem>
    <includesBooks>GEN EXO LEV NUM DEU JOS JDG RUT SA1 SA2 KI1 KI2 CH1 CH2 EZR NEH EST JOB PSA PRO ECC SNG ISA JER LAM EZE DAN HOS JOL AMO OBA JNA MIC NAH HAB ZEP HAG ZEC MAL</includesBooks>
    <webLink>https://en.wikipedia.org/wiki/Septuagint</webLink>
  </BiblePublication>

  <BiblePublication type="translation">
    <referenceAbbreviation>VUL</referenceAbbreviation>
    <languageCode>lat</languageCode>
    <publicationName lang="en">Vulgate</publicationName>
    <publicationName lang="lat">Versio Vulgata</publicationName>
    <publicationName lang="lat">Biblia Sacra Vulgata</publicationName>
    <translator>Jerome</translator>
    <translator>others</translator>
    <comment>Commissioned by Pope Damasus in 382</comment>
    <derivedFrom>HEB</derivedFrom>
    <derivedFrom>LXX</derivedFrom>
    <publicationDate>405</publicationDate>
    <versificationSystem>Vulgate</versificationSystem>
    <punctuationSystem>English</punctuationSystem>
    <bookOrderSystem>EuropeanBible</bookOrderSystem>
    <booksNamesSystem>eng_traditional</booksNamesSystem>
    <includesBooks>GEN EXO LEV NUM DEU JOS JDG RUT SA1 SA2 KI1 KI2 CH1 CH2 EZR NEH EST JOB PSA PRO ECC SNG ISA JER LAM EZE DAN HOS JOL AMO OBA JNA MIC NAH HAB ZEP HAG ZEC MAL
                    JDT TOB WIS SIR MAC
                    MAT MRK LUK JHN ACT ROM CO1 CO2 GAL EPH PHP COL TH1 TH2 TI1 TI2 TIT PHM HEB JAM PE1 PE2 JN1 JN2 JN3 JDE REV</includesBooks>
    <webLink>https://en.wikipedia.org/wiki/St_Jerome</webLink>
    <webLink>https://en.wikipedia.org/wiki/Vulgate</webLink>
    <webLink>https://en.wikipedia.org/wiki/Pope_Damasus_I</webLink>
  </BiblePublication>

  <BiblePublication type="translation">
    <referenceAbbreviation>BJ</referenceAbbreviation>
    <languageCode>ang</languageCode>
    <publicationName lang="en">Unknown</publicationName>
    <translator>The Venerable Bede</translator>
    <publicationDate>735</publicationDate>
    <versificationSystem>None</versificationSystem>
    <punctuationSystem>English</punctuationSystem>
    <bookOrderSystem>EuropeanBible</bookOrderSystem>
    <booksNamesSystem>eng_traditional</booksNamesSystem>
    <includesBooks>JHN</includesBooks>
    <webLink>https://en.wikipedia.org/wiki/Venerable_Bede</webLink>
    <webLink>https://en.wikipedia.org/wiki/List_of_works_by_Bede</webLink>
  </BiblePublication>

  <BiblePublication type="translation">
    <referenceAbbreviation>AGP</referenceAbbreviation>
    <languageCode>ang</languageCode>
    <publicationName lang="en">Unknown</publicationName>
    <translator>King Alfred the Great</translator>
    <derivedFrom>VUL</derivedFrom>
    <publicationDate>900</publicationDate>
    <versificationSystem>None</versificationSystem>
    <punctuationSystem>English</punctuationSystem>
    <bookOrderSystem>EuropeanBible</bookOrderSystem>
    <booksNamesSystem>eng_traditional</booksNamesSystem>
    <includesBooks>GEN EXO LEV NUM DEU</includesBooks>
    <webLink>https://en.wikipedia.org/wiki/Alfred_the_Great</webLink>
  </BiblePublication>

  <BiblePublication type="translation">
    <referenceAbbreviation>WYC-1382</referenceAbbreviation>
    <languageCode>enm</languageCode>
    <publicationName lang="en">Wycliffe Bible</publicationName>
    <translator>John Wycliffe</translator>
    <translator>others</translator>
    <derivedFrom>VUL</derivedFrom>
    <publicationDate>1382</publicationDate>
    <versificationSystem>None</versificationSystem>
    <punctuationSystem>English</punctuationSystem>
    <bookOrderSystem>EuropeanBible</bookOrderSystem>
    <booksNamesSystem>eng_traditional</booksNamesSystem>
    <includesBooks>GEN EXO LEV NUM DEU JOS JDG RUT SA1 SA2 KI1 KI2 CH1 CH2 EZR NEH EST JOB PSA PRO ECC SNG ISA JER LAM EZE DAN HOS JOL AMO OBA JNA MIC NAH HAB ZEP HAG ZEC MAL